### ISSUE TITLE
Not validating img urls properly

### ISSUE THREAD

**Issue by kkuciauskas** [bazaarvoice/tier3-sampling-automator#2]
Adding a letter (eg ‘S’) before Image URL (Shttps) goes through validation without errors. You can test it with feed ‘BV Updated Sampling_Nomination_Form 2020.2.26.xlsx’ from this case:
https://bazaarvoice1.lightning.force.com/lightning/r/Case/5002J00001JQs6lQAD/view

**Comment by kkuciauskas** [comment]
Bug fixed.

https://github.com/bazaarvoice/tier3-sampling-automator/commit/909a9ef1779ee372ab643d2e214c639c6488bdba

**Comment by kkuciauskas** [comment]
Reopening for @vstaskevicius to check the fix.

**Comment by vstaskevicius** [comment]
Looks good to me!
