### ISSUE TITLE
GTIN validation doesn't work

### ISSUE THREAD

**Issue by kkuciauskas** [bazaarvoice/tier3-sampling-automator#3]
After editing one of the UPCs to have 14 digits instead of 12 and tool returns empty string instead of an error.
Original UPC: 681131349475 (valid)
Edited UPC: 68113134947523 (should be invalid)

Result:
`UPCs: '',`

**Comment by kkuciauskas** [comment]
@vstaskevicius, please confirm the bug fix so I could merge the results to the master branch thereafter. Thank you.
https://github.com/bazaarvoice/tier3-sampling-automator/commit/38f69b1ae4cbc57bcba1fdc0240dee85239df4ca

**Comment by vstaskevicius** [comment]
I cannot reproduce the issue, so I believe it's fixed now. Please merge it to master!
